services:
  - type: web
    name: login-api
    env: node
    buildCommand: npm install && npm run build:server
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
    autoDeploy: true
